### ISSUE TITLE
詳細画面のレベルの表示を数字から★に変更する

### ISSUE THREAD

**Issue by shin1rok** [sho-tozawa/yugioh3#22]
レベル4の場合こんな感じで。
`★★★★(4)`

**Comment by sho-tozawa** [comment]
データを取得してレベルの数値に対応した星の数を表示する感じ？
調べたけど分からないからヒントくれ！

**Comment by shin1rok** [comment]
そうそう。
ヒント言うとほぼ答えなんだけど掛け算すればよい。

**Comment by sho-tozawa** [comment]
だめだわからん

**Comment by sho-tozawa** [comment]
@monster.level * "☆"みたいな？

**Comment by sho-tozawa** [comment]
できたわ！
文字通り掛け算て意味だったか

**Comment by shin1rok** [comment]
☆だけだと見づらいから（4）もつける方が俺は好みかな。
この辺はデザインだから好きな方にして良いよ。

**Comment by sho-tozawa** [comment]
☆だけのカード準拠で行くわ
