### ISSUE TITLE
モンスター検索機能追加

### ISSUE THREAD

**Issue by shin1rok** [sho-tozawa/yugioh3#48]
## 機能
- モンスター名で検索できる
  - like検索だとなおよい
- 星の数で検索できる
  - 星の数はテキストボックスではなく、プルダウン選択
- 攻撃力、守備力で範囲検索できる
  - 範囲検索例 ) 攻撃力1000〜4000で検索したら、攻撃力が1000〜4000のモンスター一覧が表示される

## アドバイス
いきなり全部実装すると考えることが多くて大変だから分割して実装するとよい。

**Comment by sho-tozawa** [comment]
pagenate機能と検索機能の共存ができないでござる。
ググっても事例自体が出てこない

**Comment by sho-tozawa** [comment]
application.htmlに検索機能追加して全ページに検索窓表示させるのと、searchページを用意して検索用のhtml作るのとどっちがいいかね？
今は全ページに表示させようと奮闘してる

**Comment by shin1rok** [comment]
どちらでもなくて、モンスター一覧と魔法一覧の上にそれぞれ検索フォームを入れる感じで。
理由はそれが1番簡単だから！

**Comment by shin1rok** [comment]
>pagenate機能と検索機能の共存ができないでござる。
>ググっても事例自体が出てこない

共存できるから頑張れ！

**Comment by sho-tozawa** [comment]
おk
頑張ってみるで

**Comment by shin1rok** [comment]
>pagenate機能と検索機能の共存ができないでござる。

補足
以下2つは同じ結果になる。(実行結果のSQLはrails sしたコンソールに流れる)
```
@monsters = Monster.page(params[:page]).per(10)
@monsters = Monster.all.page(params[:page]).per(10)
```

以下2つの場合のSQLの実行結果を見比べてみるとkaminariが何をしているかわかるはず。
```
@monsters = Monster.page(1).per(10)
@monsters = Monster.page(2).per(10)
```

SQLの違いがわかったら、次に確認して欲しいのが以下2つのクラス
```
puts Monster.all.class
puts Monster.where(level: 1).class
```

ここまでやってみたら検索とページネーションの共存が見えてくるはず！

**Comment by shin1rok** [comment]
>application.htmlに検索機能追加して全ページに検索窓表示させるのと、searchページを用意して検索用のhtml作るのとどっちがいいかね？

こっちも補足
>application.htmlに検索機能追加して全ページに検索窓表示させる

これをやるとモンスター検索と魔法検索の両方に対応する必要があって、その実行結果を出力する画面を作らないといけなくなる。手間がかかるし難易度が高い。

>searchページを用意して検索用のhtml作る

`全ページに検索窓表示させる`よりは簡単だけど、ちょっと考えることが増える。
(モンスターと魔法カード(とトラップカード)に1画面でどうやって対応させるか。)


いずれにしてもちゃんと考えた上で質問できてるのでとてもよい！👍
戸澤が検討してくれた案も1番簡単な実装の応用でできるからまずは簡単なやつでやっていこう。

**Comment by sho-tozawa** [comment]
rails c してputs Monster.all.classやる感じ？

**Comment by sho-tozawa** [comment]
slack通知確認
