### ISSUE TITLE
rubocop

### ISSUE THREAD

**Issue by shin1rok** [sho-tozawa/yugioh3#66]
# TODO
- [x] rubocopについて調べる
- [x] https://github.com/sho-tozawa/yugioh3/pull/65 のプルリクをdevelopにマージする
 -  Files changed で内容は確認すること
- [x] マージした後はorigin/developブランチをpullしてローカルのdevelopブランチを最新にする
- [x] rubocop導入直後は大量の警告が出るので頑張って直す
 -  feature/fix-rubocop-alertとかブランチを作って
- [x] 「RubyMine rubocop」でググってrubocopをオンにする
- [x] 以後はrubocop先生に従う

**Comment by sho-tozawa** [comment]
マージしてpull、RubyMineとrubocopの連携は完了したけど、
tozawashounoMacBook-Air:yugioh3 tozawashou$ rubocop
bash: rubocop: command not found
て出て作動しないナリ
